package ProjectEuler.Questions_11_through_20;

/*
 * Question #12
 * 
 * The sequence of triangle numbers is generated by adding the natural number. 
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The 
 * first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * 28 is divisible by 1, 2, 4, 7, 14, 28. We can see that 28 is the first triangle
 * number to have over five divisors.
 * 
 * Question: What is the value of the first triangle number to have over five 
 * hundred divisors?
 * Answer: 76576500
 */

public class Q12_HighlyDivisbleTriangularNumber {

	public static void main(String[] args) {
		int count = 0;
		int n = 1;
		int sum = 0;
		while (count < 500) {
			sum = 0;
			for (int i = n; i > 0; i--) {
				sum += i;
			}
			count = Math.max(count, getNumOfFactors(sum));
			n++;
		}
		System.out.println("Value of Triangle Number: " + sum);
	}

	private static int getNumOfFactors(int n) {
		int count = 2;
		for (int i = 2; i <= Math.round(Math.sqrt(n)); i++) {
			if (n % i == 0) {
				count += 2;
			}
		}
		return count;
	}
}
